Date formatting
Super-Repair-Bros/Super-Repair-Bros. pull request #25
Opened 2020-02-07 10:08 UTC by DDTyphos

I used the code of @ChLah . Looks good to me now

2020-02-07 10:14 UTC, ChLah requested changes
Can be improved.
My comment on the first check surely applies to the other checks too

2020-02-07 10:14 UTC, ChLah commented on Scenes/TitleScreen/TitleScreen.gd
> +
This change is unnecessary

2020-02-07 10:14 UTC, ChLah commented on Scenes/Highscore/Highscore.gd
> +		if splitup.size() > 3:
What if size() < 3? Then you would later access elements in the array, that do not exist.
Please change to != 3

2020-02-07 10:14 UTC, ChLah commented on Scenes/Highscore/Highscore.gd
> +		if splitup.size() > 3:
```suggestion
		if splitup.size() != 3:
```

2020-02-07 10:14 UTC, ChLah commented on Scenes/Highscore/Highscore.gd
> +			print("Error: splitup too big")
You can use push_error

```suggestion
			push_error("Error: Wrong format")
```

2020-02-07 10:26 UTC, DDTyphos commented on Scenes/Highscore/Highscore.gd
> +			print("Error: splitup too big")
Applied your changes.

2020-02-11 07:13 UTC, ChLah commented
Looks okay now. Gonna merge it to master and then merge this with my changes from #29.

2020-02-11 07:13 UTC, merged